### ISSUE TITLE
NotSupportedException on weaving in an empty 2019.1.0 project

### ISSUE THREAD

**Issue by Jobus0** [ByronMayne/Weaver#18] opened 2019-05-26 02:49 UTC
In a completely new and otherwise empty 2019.1.0 project, I get this error after setting it up with these simple settings:

Components:
- Weaver.PropertyChangedComponent

Weaved Assemblies:
- Library\ScriptAssemblies\Assembly-CSharp.dll

```
Exception was thrown while weaving assemblies. System.NotSupportedException: The invoked member is not supported in a dynamic module.
  at Weaver.WeaverSettings.WeaveAssemblies (System.Collections.Generic.IList`1[T] assemblies) [0x002cf] in C:\Dev\Unity Projects\Weaver Test\Assets\Weaver\Editor\Settings\WeaverSettings.cs:273 
  at Weaver.WeaverSettings.CheckForAssemblyModifications () [0x00169] in C:\Dev\Unity Projects\Weaver Test\Assets\Weaver\Editor\Settings\WeaverSettings.cs:192 
UnityEngine.Debug:LogError(Object)
Weaver.Log:Error(String, String, Boolean, Int32) (at Assets/Weaver/Editor/Utility Types/Logging/Log.cs:95)
Weaver.WeaverSettings:CheckForAssemblyModifications() (at Assets/Weaver/Editor/Settings/WeaverSettings.cs:208)
UnityEditor.AssemblyReloadEvents:OnBeforeAssemblyReload()
```
[Weaver Test.zip](https://github.com/ByronMayne/Weaver/files/3219938/Weaver.Test.zip)

**Comment by ByronMayne** [comment] 2019-05-26 12:27
Hey Jobus,

I have not tried Weaver on 2019 but I will download it and look into this. Googling the exception it just looks that I am trying to get a path of a dynamic assembly. I will patch it and provide an update. 

Cheers,
Byron

**Comment by ByronMayne** [comment] 2019-05-26 14:46
The issue is that the `.mdb` file is now created after `AssemblyReloadEvents.beforeAssemblyReload` event instead of before like it has been for many Unity versions. We can run weaver without the debug symbols however that means if you get an exception in a class that Weaver touches your callstack will be wrong.

**Comment by ByronMayne** [comment] 2019-05-26 15:25
Unfortunately this is a bug by Unity and I opened an bug report. I can't delay until after the callback is invoke otherwise I get a sharing violation because Unity is now using these assemblies that I am trying to modify. For now you can just set `writerParameters.WriteSymbols = false;` inside of `WeaverSettings`. This is not ideal but unfortunately my hands are tied.

**Comment by Jobus0** [comment] 2019-05-26 16:10
I'm still getting the error with `writerParameters.WriteSymbols = false;` on WeaverSettings:235.

I should note that Unity 2018.3.0 also has this issue.

**Comment by ByronMayne** [comment] 2019-05-29 16:31
Yeah I am not sure which version they changed the order of assembly loading. I am playing around with some thing to see if I can get it to work however I am a slave to the unity reloading event. Unity write all assemblies and then the next frame it loads them. Weaver needs to read in between that frame otherwise they will be replaced or you will get a exception since the assemblies are now being used.

**Comment by Jobus0** [comment] 2019-05-29 17:51
Check out [Mirror's weaver](https://github.com/vis2k/Mirror/tree/master/Assets/Mirror/Editor/Weaver), it listens to the [CompilationPipeline.assemblyCompilationFinished](https://docs.unity3d.com/ScriptReference/Compilation.CompilationPipeline-assemblyCompilationFinished.html) event to run its weaving, if that helps at all.

**Comment by ByronMayne** [comment] 2019-05-29 17:56
That looks like it might work, I will check it out when I get home. If you want to replace the callback to check locally you can replace it in `WeaverSettings.cs`
```csharp 
#if UNITY_2017_1_OR_NEWER
            AssemblyReloadEvents.beforeAssemblyReload += CheckForAssemblyModifications;
#else
            m_Log.Warning("Dynamic Assembly Reload not support until Unity 2017. Enter play mode to reload assemblies to see the effects of Weaving.", false);
#endif
```

Thanks,

**Comment by ben-rasooli** [comment] 2019-07-10 10:02
Hi. I'm getting the same exception. I'm using Unity 2019.1.0f2 and your latest commit. Any idea how I might fix it?

Thanks

**Comment by ByronMayne** [comment] 2019-07-14 05:15
Unfortunately at this point due to the Unity callback order we can't weave assemblies. Unity's callback for when assemblies are modified happens before they release the lock and write the pdbs. Weaver needs to write at the point where the lock is released but before they are loaded. 

The only way to get around this might to to inject code into the Unity assemblies but that is far from ideal.

**Comment by nlebedenco** [comment] 2019-08-11 01:28
Funny cause I'm using 2019.1.11f now and I don't seem to be experiencing any special difficulties trying to weave Library\ScriptAssemblies\Assembly-CSharp.dll in the editor or in the build. Tested using MethodTimer. Only difference is that I'm using a [fork](https://github.com/drunken-lemurs/Weaver/tree/upm-0.9.0-preview) of the Weaver where I stripped Mono.Cecil and anything that wouldn't belong in a Unity Package. No significant code changes though, I believe. Then I defined unity's Mono.Cecil package as a dependency. I also moved attributes and custom WeaverComponents out of the package to separate assemblies (using asmdefs) that live in the Assets folder of my project.

**Comment by ByronMayne** [comment] 2019-08-11 16:17
Yeah I am testing on `2019.3.0a3` and I have the same local changes you have above.  As you  can see in this screen shot the assemblyComplicationFinished has been invoked and the path given is `Library/ScriptAssemblies/Assembly-CSharp.dll` and yet that folder is empty. It happens later on in the frame, which is inaccessible to Weaver. 
![image](https://user-images.githubusercontent.com/6024487/62836501-a50ca700-bc31-11e9-95c1-21b0465ef637.png).

**Comment by ByronMayne** [comment] 2019-08-11 16:41
However I just tried to do the same thing in am empty project and it worked fine. I was missing the assembly definitions.

**Comment by ByronMayne** [comment] 2019-11-24 23:14
Fixed with my latest push

**Closed by ByronMayne** 2019-11-24 23:14 UTC
Labels: bug
